# Generated by Django 5.0.7 on 2024-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_tagpost_alter_women_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='women.tagpost'),
        ),
    ]
